language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

install:
  - composer install

before_script:
  - sudo apt-get update
  - sudo apt-get install nginx
  - sudo cp tests/_scripts/.travis_nginx.conf /etc/nginx/nginx.conf
  - sudo /etc/init.d/nginx restart
  - git clone https://github.com/vanilla/addons.git
  - composer global require 'codeception/codeception=*'
#  - vendor/bin/phpcs --config-set default_standard addons/standards/Vanilla

script:
  # Check coding standards compliance
  - ~/.composer/vendor/vendor/bin/codecept run  # self tests
#  - vendor/bin/phpcs ./library/core
#  - vendor/bin/phpcs ./applications
#  - vendor/bin/phpcs ./plugins

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
